### ISSUE TITLE
About the differences on the training strategies when "_pt" in model name or not.

### ISSUE THREAD

**Issue by xiaovhua** [aywi/mprotonet#1]
Thank you so much for your prominent work in your MProtoNet, and sincerely thank you for your code available on Github too. 

Recently, we have some doubts about the usage of (a) "_pt" in model name and (b) best_grid["fixed"] in tumor_cls.py. 

In the commands you supply in the repository, the model names all end with "_pmX". Therefore, according to the code, MProtoNet will update in mode "joint" and "last_layer" (every 10 epochs) while training. However, we notice that when "_pt" is in the model name and best_grid["fixed"]=False, there is also another branch, where the net.features will not update at the begging, but start to optimize when current epoch >=  wu_e. We also notice that the vanilla ProtoPNet updates in the latter way (fix the net.features at the begging).  

Will there be a significant difference between two kinds of training strategies? Hope to receive your kindest reply!

**Comment by aywi** [comment]
It is kind of our fault for not cleaning up these code, since these options are defined for models that are deleted in the final paper.

1. "_pt" means "pre-trained" models that we tested before, which are 2D & 3D mixed models where their 2D layers are pre-trained with Imagenet1k. Since we test pure 3D models in the final paper, these models are deleted for fair comparisons. You can also see that in the final experiments we choose feature layers all with "_ri", which means "randomly initialized" (pre-trained versions are ignored since we only use these 2D backbones from torchvision as sketches to build 3D feature layers):
https://github.com/aywi/mprotonet/blob/4565e22a0c3a15f744e184ce91d9f4a0c87fae9a/src/models.py#L27-L47
2. "fixed" is a much older option when I tested the pre-trained models without a fixed training period in the beginning (yes, the correct name should be "not fixed").
3. Vanilla ProtoPNet has a fixed training period because it is a 2D model pre-trained with Imagenet1k. Since we test pure 3D models that are randomly initialized in the final paper, this period becomes useless and only wastes training time.

So, in a word, just ignore them. I will add a commit later to remove these code.

**Comment by xiaovhua** [comment]
> It is kind of our fault for not cleaning up these code, since these options are defined for models that are deleted in the final paper.
> 
> 1. "_pt" means "pre-trained" models that we tested before, which are 2D & 3D mixed models where their 2D layers are pre-trained with Imagenet1k. Since we test pure 3D models in the final paper, these models are deleted for fair comparisons. You can also see that in the final experiments we choose feature layers all with "_ri", which means "randomly initialized" (pre-trained versions are ignored since we only use these 2D backbones from torchvision as sketches to build 3D feature layers):
>    https://github.com/aywi/mprotonet/blob/4565e22a0c3a15f744e184ce91d9f4a0c87fae9a/src/models.py#L27-L47
> 2. "fixed" is a much older option when I tested the pre-trained models without a fixed training period in the beginning (yes, the correct name should be "not fixed").
> 3. Vanilla ProtoPNet has a fixed training period because it is a 2D model pre-trained with Imagenet1k. Since we test pure 3D models that are randomly initialized in the final paper, this period becomes useless and only wastes training time.
> 
> So, in a word, just ignore them. I will add a commit later to remove these code.

I get it! Thank you so much!
