### ISSUE TITLE
Experiment-related parameter settings

### ISSUE THREAD

**Issue by Yvette908** [aywi/mprotonet#2]
Dear author, hello. Thank you for your work. We've had some issues reproducing your work. 
tumor_cls.py the "if 'MProtoNet' in model_name:
        return train_mppnet(net, data_loader, optimizer, coefs=grid['coefs'], **kwargs)", we can't seem to find the "coefs" key present in the grid. Is there any solution, I look forward to your reply, thank you!

**Comment by aywi** [comment]
`grid` is from:
https://github.com/aywi/mprotonet/blob/4f337811f044b1bdf7c663378a205fc9d945edd6/src/tumor_cls.py#L508-L509
and since I didn't implement inner-loop cross-validation, the `best_grid` is the same as `param_grid`:
https://github.com/aywi/mprotonet/blob/4f337811f044b1bdf7c663378a205fc9d945edd6/src/tumor_cls.py#L340-L344
https://github.com/aywi/mprotonet/blob/4f337811f044b1bdf7c663378a205fc9d945edd6/src/tumor_cls.py#L273-L277
https://github.com/aywi/mprotonet/blob/4f337811f044b1bdf7c663378a205fc9d945edd6/src/tumor_cls.py#L226-L227
`param_grid` must be passed from the command line (`-p` or `--param-grid`), as shown in the examples on https://github.com/aywi/mprotonet#experiments. You can find `coefs` right there:
```sh
# MProtoNet C
python ./tumor_cls.py -m MProtoNet3D_pm5 -n 100 -p "{'batch_size': [32], 'lr': [0.001], 'wd': [0.01], 'features': ['resnet152_ri'], 'n_layers': [6], 'prototype_shape': [(30, 128, 1, 1, 1)], 'f_dist': ['cos'], 'topk_p': [1], 'coefs': [{'cls': 1, 'clst': 0.8, 'sep': -0.08, 'L1': 0.01, 'map': 0.5, 'OC': 0.05}]}" --save-model 1
```
